export function Footer() {
  return (
    <footer className="border-t border-zinc-800 bg-zinc-950 py-8">
      <div className="mx-auto max-w-7xl px-4 text-center text-sm text-zinc-500">
        <p>
          BS Meter — Cutting through the content so you don&apos;t have to.
        </p>
        <p className="mt-2">
          Scores generated by AI analysis of trusted reviewer transcripts, time
          data, and review sentiment.
        </p>
      </div>
    </footer>
  );
}
